"""
Lesson views — GET lesson detail, POST answer, POST hint.

Design notes:
- Lessons are generated by the Lesson_Generator skill and cached in the in-memory
  lesson_stub_store keyed by lesson_id. This ensures the same lesson is returned
  on repeated GET requests (and the answer_key is available for evaluation).
- The answer_key is NEVER returned to the frontend — it stays in the cache only.
- Answer evaluation and hints are handled by the Socratic_Tutor skill.
- Progress is tracked via the Progress_Updater skill and persisted in-memory.
"""

import json

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from agent.runner import AgentError, run_skill
from utils.fixtures import (
    get_placeholder_evaluation,
    get_placeholder_hint,
    get_placeholder_lesson,
)
from utils.lesson_state import (
    calculate_stars,
    safe_transition_status,
    InvalidTransitionError,
)
from utils.lesson_stub_store import get_lesson, save_lesson
from utils.progress_store import (
    get_lesson_progress,
    update_lesson_progress,
)


_DEFAULT_USER = "anonymous"


def _get_user_id(request) -> str:
    auth = request.META.get("HTTP_AUTHORIZATION", "")
    if auth.startswith("Bearer "):
        return auth[7:].strip() or _DEFAULT_USER
    return _DEFAULT_USER


def _strip_answer_keys(lesson: dict) -> dict:
    """Return a copy of the lesson with answer_key removed from all questions."""
    safe = dict(lesson)
    safe["questions"] = [
        {k: v for k, v in q.items() if k != "answer_key"}
        for q in lesson.get("questions", [])
    ]
    return safe


@csrf_exempt
@require_http_methods(["GET"])
def lesson_detail(request, lesson_id: str):
    """
    GET /api/lessons/{lesson_id}

    Returns lesson micro-theory and questions (no answer keys).
    If the lesson is not in the cache, generates it via the Lesson_Generator skill.
    Query params:
        module_topic: used to generate the lesson if it isn't cached yet
        mode: learn|solve (default: learn)
    """
    cached = get_lesson(lesson_id)
    if cached:
        return JsonResponse(_strip_answer_keys(cached))

    module_topic = request.GET.get("module_topic", "General Topic").strip()
    mode = request.GET.get("mode", "learn").strip()
    if mode not in ("learn", "solve"):
        mode = "learn"

    try:
        lesson = run_skill(
            "lesson_generator",
            mode=mode,
            module_topic=module_topic,
        )
    except AgentError:
        lesson = get_placeholder_lesson(module_topic, mode=mode)

    lesson["lesson_id"] = lesson_id
    save_lesson(lesson_id, lesson)

    return JsonResponse(_strip_answer_keys(lesson))


@csrf_exempt
@require_http_methods(["POST"])
def lesson_answer(request, lesson_id: str):
    """
    POST /api/lessons/{lesson_id}/answer

    Body: { "question_id": string, "answer": string }
    Response: { "correct": bool, "next_prompt": string, "progress": {...} }

    Uses the Socratic_Tutor for evaluation and the Progress_Updater for
    consistent XP/stars computation with safety-checked state transitions.
    """
    try:
        payload = json.loads(request.body or "{}")
    except json.JSONDecodeError:
        return JsonResponse({"detail": "Invalid JSON payload."}, status=400)

    question_id = str(payload.get("question_id", "")).strip()
    student_answer = str(payload.get("answer", "")).strip()

    if not question_id or not student_answer:
        return JsonResponse({"detail": "question_id and answer are required."}, status=400)

    user_id = _get_user_id(request)
    cached = get_lesson(lesson_id)
    question_prompt = ""
    answer_key = ""
    if cached:
        for q in cached.get("questions", []):
            if q.get("id") == question_id:
                question_prompt = q.get("prompt", "")
                answer_key = q.get("answer_key", "")
                break

    try:
        evaluation = run_skill(
            "socratic_tutor",
            mode="learn",
            student_answer=student_answer,
            question_prompt=f"{question_prompt}\nExpected: {answer_key}",
            hint_level=0,
        )
    except AgentError:
        evaluation = get_placeholder_evaluation(correct=bool(answer_key and student_answer))

    correct = evaluation.get("correct", False)
    total_questions = len(cached.get("questions", [])) if cached else 3

    lesson_prog = get_lesson_progress(user_id, lesson_id)
    answered_count = len(lesson_prog.answered_questions) + (1 if correct else 0)

    new_status = safe_transition_status(
        lesson_prog.status, answered_count, total_questions
    )

    hint_usage = max(
        (a.hint_level for a in lesson_prog.attempts if a.question_id == question_id),
        default=0,
    )

    try:
        progress_result = run_skill(
            "progress_updater",
            mode="learn",
            correctness=correct,
            hint_usage=hint_usage,
            timing_seconds=0,
            current_xp=lesson_prog.xp_earned,
            current_status=lesson_prog.status,
            answered_count=answered_count,
            total_questions=total_questions,
        )
    except AgentError:
        from utils.lesson_state import calculate_xp
        xp = calculate_xp(correct=correct, hint_level=hint_usage)
        progress_result = {
            "xp_earned": xp,
            "total_xp": lesson_prog.xp_earned + xp,
            "stars_remaining": calculate_stars(hint_usage=hint_usage),
            "status": new_status,
            "correctness": correct,
        }

    update_lesson_progress(
        user_id=user_id,
        lesson_id=lesson_id,
        question_id=question_id,
        answer=student_answer,
        correct=correct,
        hint_level=hint_usage,
        xp_earned=progress_result["xp_earned"],
        stars_remaining=progress_result["stars_remaining"],
        new_status=progress_result["status"],
    )

    return JsonResponse({
        "correct": correct,
        "next_prompt": evaluation.get("next_prompt", ""),
        "progress": {
            "xp": progress_result["total_xp"],
            "stars_remaining": progress_result["stars_remaining"],
            "status": progress_result["status"],
        },
    })


@csrf_exempt
@require_http_methods(["POST"])
def lesson_hint(request, lesson_id: str):
    """
    POST /api/lessons/{lesson_id}/hint

    Body: { "question_id": string, "hint_level": int }
    Response: { "hint": string, "stars_remaining": int }
    """
    try:
        payload = json.loads(request.body or "{}")
    except json.JSONDecodeError:
        return JsonResponse({"detail": "Invalid JSON payload."}, status=400)

    question_id = str(payload.get("question_id", "")).strip()
    hint_level = int(payload.get("hint_level", 1))
    hint_level = max(1, min(hint_level, 3))

    cached = get_lesson(lesson_id)
    question_prompt = ""
    if cached:
        for q in cached.get("questions", []):
            if q.get("id") == question_id:
                question_prompt = q.get("prompt", "")
                break

    try:
        evaluation = run_skill(
            "socratic_tutor",
            mode="learn",
            student_answer="",
            question_prompt=question_prompt,
            hint_level=hint_level,
        )
        hint_text = evaluation.get("hint") or evaluation.get("next_prompt", "")
    except AgentError:
        fallback = get_placeholder_hint(hint_level)
        hint_text = fallback["hint"]

    stars_remaining = calculate_stars(hint_usage=hint_level)

    return JsonResponse({
        "hint": hint_text,
        "stars_remaining": stars_remaining,
    })
