"""
Lesson views - GET lesson detail, POST answer, POST hint.

Design notes:
- Lessons are generated by the Lesson_Generator skill and cached in the in-memory
  lesson_stub_store keyed by lesson_id. This ensures the same lesson is returned
  on repeated GET requests (and the answer_key is available for evaluation).
- The answer_key is NEVER returned to the frontend — it stays in the cache only.
- Answer evaluation and hints are handled by the Socratic_Tutor skill.
- Progress is tracked via the Progress_Updater skill and persisted in-memory.
"""

import json

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from agent.runner import AgentError, run_skill
from apps.lessons.models import Lesson
from apps.lessons.services import (
    ensure_lesson_state,
    ensure_question,
    get_authenticated_user,
    get_hint_count,
    get_question,
    normalize_mode,
    record_answer_attempt,
    record_hint_attempt,
)
from utils.fixtures import (
    get_placeholder_evaluation,
    get_placeholder_hint,
    get_placeholder_lesson,
)
from utils.lesson_state import (
    calculate_stars,
    calculate_xp,
    safe_transition_status,
    InvalidTransitionError,
)
from utils.lesson_stub_store import get_lesson, save_lesson
from utils.progress_store import (
    get_lesson_progress,
    update_lesson_progress,
)


_DEFAULT_USER = "anonymous"


def _get_user_id(request) -> str:
    auth = request.META.get("HTTP_AUTHORIZATION", "")
    if auth.startswith("Bearer "):
        return auth[7:].strip() or _DEFAULT_USER
    return _DEFAULT_USER


def _strip_answer_keys(lesson: dict) -> dict:
    """Return a copy of the lesson with answer_key removed from all questions."""
    safe = dict(lesson)
    safe["questions"] = [
        {k: v for k, v in question.items() if k != "answer_key"}
        for question in lesson.get("questions", [])
    ]
    return safe


def _ensure_cached_lesson(lesson_id: str, module_topic: str, mode: str) -> dict:
    cached = get_lesson(lesson_id)
    if cached is not None:
        return cached

    try:
        lesson = run_skill(
            "lesson_generator",
            mode=mode,
            module_topic=module_topic,
        )
    except AgentError:
        lesson = get_placeholder_lesson(module_topic, mode=mode)

    lesson["lesson_id"] = lesson_id
    lesson["title"] = module_topic
    lesson["module_topic"] = module_topic
    save_lesson(lesson_id, lesson)
    return get_lesson(lesson_id) or lesson


def _get_cached_question(cached: dict | None, question_id: str) -> tuple[str, str]:
    for question in (cached or {}).get("questions", []):
        if question.get("id") == question_id:
            return str(question.get("prompt", "")), str(question.get("answer_key", ""))
    return "", ""


@csrf_exempt
@require_http_methods(["GET"])
def lesson_detail(request, lesson_id: str):
    """
    GET /api/lessons/{lesson_id}

    Returns lesson micro-theory and questions (no answer keys).
    If the lesson is not in the cache, generates it via the Lesson_Generator skill.
    Query params:
        module_topic: used to generate the lesson if it isn't cached yet
        mode: learn|solve (default: learn)
    """
    user = get_authenticated_user(request)
    module_topic = request.GET.get("module_topic", "General Topic").strip()
    mode = normalize_mode(request.GET.get("mode", "learn"))

    cached = _ensure_cached_lesson(lesson_id, module_topic, mode)

    if user is None:
        return JsonResponse(_strip_answer_keys(cached))

    lesson_record = Lesson.objects.prefetch_related("questions").filter(lesson_key=lesson_id).first()
    if lesson_record is not None:
        ensure_lesson_state(user, lesson_record)

    return JsonResponse(_strip_answer_keys(cached))


@csrf_exempt
@require_http_methods(["POST"])
def lesson_answer(request, lesson_id: str):
    """
    POST /api/lessons/{lesson_id}/answer

    Body: { "question_id": string, "answer": string }
    Response: { "correct": bool, "next_prompt": string, "progress": {...} }

    Uses the Socratic_Tutor for evaluation and the Progress_Updater for
    consistent XP/stars computation with safety-checked state transitions.
    """
    user = get_authenticated_user(request)

    try:
        payload = json.loads(request.body or "{}")
    except json.JSONDecodeError:
        return JsonResponse({"detail": "Invalid JSON payload."}, status=400)

    question_id = str(payload.get("question_id", "")).strip()
    student_answer = str(payload.get("answer", "")).strip()

    if not question_id or not student_answer:
        return JsonResponse({"detail": "question_id and answer are required."}, status=400)

    module_topic = request.GET.get("module_topic", "General Topic").strip()
    mode = normalize_mode(request.GET.get("mode", "learn"))
    cached = _ensure_cached_lesson(lesson_id, module_topic, mode)

    if user is None:
        question_prompt, answer_key = _get_cached_question(cached, question_id)
        legacy_user_id = _get_user_id(request)
        lesson_prog = get_lesson_progress(legacy_user_id, lesson_id)
        total_questions = len(cached.get("questions", [])) if cached else 3
        answered_count = len(lesson_prog.answered_questions)

        try:
            evaluation = run_skill(
                "socratic_tutor",
                mode="learn",
                student_answer=student_answer,
                question_prompt=f"{question_prompt}\nExpected: {answer_key}",
                hint_level=0,
            )
        except AgentError:
            evaluation = get_placeholder_evaluation(correct=bool(answer_key and student_answer))

        correct = evaluation.get("correct", False)
        answered_count = answered_count + (1 if correct else 0)
        new_status = safe_transition_status(lesson_prog.status, answered_count, total_questions)

        hint_usage = max(
            (attempt.hint_level for attempt in lesson_prog.attempts if attempt.question_id == question_id),
            default=0,
        )

        try:
            progress_result = run_skill(
                "progress_updater",
                mode="learn",
                correctness=correct,
                hint_usage=hint_usage,
                timing_seconds=0,
                current_xp=lesson_prog.xp_earned,
                current_status=lesson_prog.status,
                answered_count=answered_count,
                total_questions=total_questions,
            )
        except AgentError:
            xp = calculate_xp(correct=correct, hint_level=hint_usage)
            progress_result = {
                "xp_earned": xp,
                "total_xp": lesson_prog.xp_earned + xp,
                "stars_remaining": calculate_stars(hint_usage),
                "status": new_status,
                "correctness": correct,
            }

        update_lesson_progress(
            user_id=legacy_user_id,
            lesson_id=lesson_id,
            question_id=question_id,
            answer=student_answer,
            correct=correct,
            hint_level=hint_usage,
            xp_earned=progress_result["xp_earned"],
            stars_remaining=progress_result["stars_remaining"],
            new_status=progress_result["status"],
        )

        return JsonResponse({
            "correct": correct,
            "next_prompt": evaluation.get("next_prompt", ""),
            "progress": {
                "xp": progress_result["total_xp"],
                "stars_remaining": progress_result["stars_remaining"],
                "status": progress_result["status"],
            },
        })

    lesson_record = Lesson.objects.prefetch_related("questions").filter(lesson_key=lesson_id).first()
    if lesson_record is None:
        return JsonResponse({"detail": "Lesson not found."}, status=404)

    question_record = get_question(lesson_record, question_id)
    if question_record is None:
        question_record = ensure_question(lesson_record, question_id)

    state = ensure_lesson_state(user, lesson_record)
    question_prompt = question_record.prompt
    answer_key = question_record.answer_key
    hint_count = get_hint_count(state, question_record)

    try:
        evaluation = run_skill(
            "socratic_tutor",
            mode="learn",
            student_answer=student_answer,
            question_prompt=f"{question_prompt}\nExpected: {answer_key}",
            hint_level=0,
        )
    except AgentError:
        evaluation = get_placeholder_evaluation(correct=bool(answer_key and student_answer))

    correct = evaluation.get("correct", False)
    progress = record_answer_attempt(
        state=state,
        question=question_record,
        answer=student_answer,
        correct=correct,
        hint_count=hint_count,
    )

    return JsonResponse({
        "correct": correct,
        "next_prompt": evaluation.get("next_prompt", ""),
        "progress": progress,
    })


@csrf_exempt
@require_http_methods(["POST"])
def lesson_hint(request, lesson_id: str):
    """
    POST /api/lessons/{lesson_id}/hint

    Body: { "question_id": string, "hint_level": int }
    Response: { "hint": string, "stars_remaining": int }
    """
    user = get_authenticated_user(request)

    try:
        payload = json.loads(request.body or "{}")
    except json.JSONDecodeError:
        return JsonResponse({"detail": "Invalid JSON payload."}, status=400)

    question_id = str(payload.get("question_id", "")).strip()
    hint_level = int(payload.get("hint_level", 1))
    hint_level = max(1, min(hint_level, 3))

    module_topic = request.GET.get("module_topic", "General Topic").strip()
    mode = normalize_mode(request.GET.get("mode", "learn"))
    cached = _ensure_cached_lesson(lesson_id, module_topic, mode)

    if user is None:
        question_prompt, _ = _get_cached_question(cached, question_id)
        try:
            evaluation = run_skill(
                "socratic_tutor",
                mode="learn",
                student_answer="",
                question_prompt=question_prompt,
                hint_level=hint_level,
            )
            hint_text = evaluation.get("hint") or evaluation.get("next_prompt", "")
        except AgentError:
            fallback = get_placeholder_hint(hint_level)
            hint_text = fallback["hint"]

        return JsonResponse({
            "hint": hint_text,
            "stars_remaining": max(0, 3 - hint_level),
        })

    lesson_record = Lesson.objects.prefetch_related("questions").filter(lesson_key=lesson_id).first()
    if lesson_record is None:
        return JsonResponse({"detail": "Lesson not found."}, status=404)

    question_record = get_question(lesson_record, question_id)
    if question_record is None:
        question_record = ensure_question(lesson_record, question_id)

    state = ensure_lesson_state(user, lesson_record)
    question_prompt = question_record.prompt

    try:
        evaluation = run_skill(
            "socratic_tutor",
            mode="learn",
            student_answer="",
            question_prompt=question_prompt,
            hint_level=hint_level,
        )
        hint_text = evaluation.get("hint") or evaluation.get("next_prompt", "")
    except AgentError:
        fallback = get_placeholder_hint(hint_level)
        hint_text = fallback["hint"]

    stars_remaining = record_hint_attempt(state=state, question=question_record, hint_level=hint_level)

    return JsonResponse({
        "hint": hint_text,
        "stars_remaining": stars_remaining,
    })
