"""
Lesson views — GET lesson detail, POST answer, POST hint.

Design notes:
- Lessons are generated by the Lesson_Generator skill and cached in the in-memory
  lesson_stub_store keyed by lesson_id. This ensures the same lesson is returned
  on repeated GET requests (and the answer_key is available for evaluation).
- The answer_key is NEVER returned to the frontend — it stays in the cache only.
- Answer evaluation and hints are handled by the Socratic_Tutor skill.
"""

import json

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from agent.runner import AgentError, run_skill
from utils.fixtures import (
    get_placeholder_evaluation,
    get_placeholder_hint,
    get_placeholder_lesson,
)
from utils.lesson_state import calculate_xp, calculate_stars, transition_status
from utils.lesson_stub_store import get_lesson, save_lesson


def _strip_answer_keys(lesson: dict) -> dict:
    """Return a copy of the lesson with answer_key removed from all questions."""
    safe = dict(lesson)
    safe["questions"] = [
        {k: v for k, v in q.items() if k != "answer_key"}
        for q in lesson.get("questions", [])
    ]
    return safe


@csrf_exempt
@require_http_methods(["GET"])
def lesson_detail(request, lesson_id: str):
    """
    GET /api/lessons/{lesson_id}

    Returns lesson micro-theory and questions (no answer keys).
    If the lesson is not in the cache, generates it via the Lesson_Generator skill.
    Query params:
        module_topic: used to generate the lesson if it isn't cached yet
        mode: learn|solve (default: learn)
    """
    cached = get_lesson(lesson_id)
    if cached:
        return JsonResponse(_strip_answer_keys(cached))

    module_topic = request.GET.get("module_topic", "General Topic").strip()
    mode = request.GET.get("mode", "learn").strip()
    if mode not in ("learn", "solve"):
        mode = "learn"

    try:
        lesson = run_skill(
            "lesson_generator",
            mode=mode,
            module_topic=module_topic,
        )
    except AgentError:
        lesson = get_placeholder_lesson(module_topic, mode=mode)

    # Override the lesson_id with the one from the URL so the link is stable.
    lesson["lesson_id"] = lesson_id
    save_lesson(lesson_id, lesson)

    return JsonResponse(_strip_answer_keys(lesson))


@csrf_exempt
@require_http_methods(["POST"])
def lesson_answer(request, lesson_id: str):
    """
    POST /api/lessons/{lesson_id}/answer

    Body: { "question_id": string, "answer": string }
    Response: { "correct": bool, "next_prompt": string, "progress": {...} }
    """
    try:
        payload = json.loads(request.body or "{}")
    except json.JSONDecodeError:
        return JsonResponse({"detail": "Invalid JSON payload."}, status=400)

    question_id = str(payload.get("question_id", "")).strip()
    student_answer = str(payload.get("answer", "")).strip()

    if not question_id or not student_answer:
        return JsonResponse({"detail": "question_id and answer are required."}, status=400)

    # Look up the lesson and find the question's answer_key for context
    cached = get_lesson(lesson_id)
    question_prompt = ""
    answer_key = ""
    if cached:
        for q in cached.get("questions", []):
            if q.get("id") == question_id:
                question_prompt = q.get("prompt", "")
                answer_key = q.get("answer_key", "")
                break

    try:
        evaluation = run_skill(
            "socratic_tutor",
            mode="learn",
            student_answer=student_answer,
            question_prompt=f"{question_prompt}\nExpected: {answer_key}",
            hint_level=0,
        )
    except AgentError:
        evaluation = get_placeholder_evaluation(correct=bool(answer_key and student_answer))

    correct = evaluation.get("correct", False)
    xp = calculate_xp(correct=correct, hint_level=0)
    stars = calculate_stars(hint_usage=0)
    total_questions = len(cached.get("questions", [])) if cached else 3
    status = transition_status("in_progress", 1, total_questions)

    return JsonResponse({
        "correct": correct,
        "next_prompt": evaluation.get("next_prompt", ""),
        "progress": {
            "xp": xp,
            "stars_remaining": stars,
            "status": status,
        },
    })


@csrf_exempt
@require_http_methods(["POST"])
def lesson_hint(request, lesson_id: str):
    """
    POST /api/lessons/{lesson_id}/hint

    Body: { "question_id": string, "hint_level": int }
    Response: { "hint": string, "stars_remaining": int }
    """
    try:
        payload = json.loads(request.body or "{}")
    except json.JSONDecodeError:
        return JsonResponse({"detail": "Invalid JSON payload."}, status=400)

    question_id = str(payload.get("question_id", "")).strip()
    hint_level = int(payload.get("hint_level", 1))
    hint_level = max(1, min(hint_level, 3))  # clamp to 1-3

    # Look up question context for the tutor
    cached = get_lesson(lesson_id)
    question_prompt = ""
    answer_key = ""
    if cached:
        for q in cached.get("questions", []):
            if q.get("id") == question_id:
                question_prompt = q.get("prompt", "")
                answer_key = q.get("answer_key", "")
                break

    try:
        evaluation = run_skill(
            "socratic_tutor",
            mode="learn",
            student_answer="",
            question_prompt=question_prompt,
            hint_level=hint_level,
        )
        hint_text = evaluation.get("hint") or evaluation.get("next_prompt", "")
    except AgentError:
        fallback = get_placeholder_hint(hint_level)
        hint_text = fallback["hint"]

    stars_remaining = calculate_stars(hint_usage=hint_level)

    return JsonResponse({
        "hint": hint_text,
        "stars_remaining": stars_remaining,
    })
